FROM debian:stretch as builder
COPY --from=amd64/busybox:1.31.1 /bin/busybox /bin/busybox
RUN chmod 555 /bin/busybox \
 && /bin/busybox --install -s /usr/local/bin

FROM fluent/fluent-bit:latest
COPY --from=builder /bin/busybox /bin/
COPY --from=builder /usr/local/bin/ /usr/local/bin/
